package eu.eurogestion.ese.domain;
// Generated 11-feb-2019 14:05:28 by Hibernate Tools 5.2.11.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", catalog = "eSe")
public class Cargo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idCargo;
	private String nombre;
	private String descripcion;
	private List<Personal> personales;

	public Cargo() {
	}

	public Cargo(int idCargo) {
		this.idCargo = idCargo;
	}

	public Cargo(int idCargo, String nombre, String descripcion, List<Personal> personales) {
		this.idCargo = idCargo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.personales = personales;
	}

	@Id

	@Column(name = "id_cargo", unique = true, nullable = false)
	public int getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(int idCargo) {
		this.idCargo = idCargo;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public List<Personal> getPersonales() {
		return personales;
	}

	public void setPersonales(List<Personal> personales) {
		this.personales = personales;
	}

}
