package eu.eurogestion.ese.domain;
// Generated 11-feb-2019 14:05:28 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name = "compania", catalog = "eSe")
public class Compania implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idCompania;
	private String nombre;
	private int tipoCompania;
	private String documento;
	private String tipoVia;
	private String via;
	private Integer numero;
	private Integer planta;
	private String puerta;
	private Boolean bajaLogica;
	private Date fechaBaja;
	private List<Personal> personales;

	public Compania() {
	}

	public Compania(int idCompania, String nombre, int tipoCompania, String documento) {
		this.idCompania = idCompania;
		this.nombre = nombre;
		this.tipoCompania = tipoCompania;
		this.documento = documento;
	}

	public Compania(int idCompania, String nombre, int tipoCompania, String documento, String tipoVia, String via,
			Integer numero, Integer planta, String puerta, Boolean bajaLogica, Date fechaBaja,
			List<Personal> personales) {
		this.idCompania = idCompania;
		this.nombre = nombre;
		this.tipoCompania = tipoCompania;
		this.documento = documento;
		this.tipoVia = tipoVia;
		this.via = via;
		this.numero = numero;
		this.planta = planta;
		this.puerta = puerta;
		this.bajaLogica = bajaLogica;
		this.fechaBaja = fechaBaja;
		this.personales = personales;
	}

	@Id

	@Column(name = "id_compania", unique = true, nullable = false)
	public int getIdCompania() {
		return this.idCompania;
	}

	public void setIdCompania(int idCompania) {
		this.idCompania = idCompania;
	}

	@Column(name = "nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo_compania", nullable = false)
	public int getTipoCompania() {
		return this.tipoCompania;
	}

	public void setTipoCompania(int tipoCompania) {
		this.tipoCompania = tipoCompania;
	}

	@Column(name = "documento", nullable = false, length = 14)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "tipo_via", length = 10)
	public String getTipoVia() {
		return this.tipoVia;
	}

	public void setTipoVia(String tipoVia) {
		this.tipoVia = tipoVia;
	}

	@Column(name = "via", length = 30)
	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "planta")
	public Integer getPlanta() {
		return this.planta;
	}

	public void setPlanta(Integer planta) {
		this.planta = planta;
	}

	@Column(name = "puerta", length = 10)
	public String getPuerta() {
		return this.puerta;
	}

	public void setPuerta(String puerta) {
		this.puerta = puerta;
	}

	@Column(name = "baja_logica")
	public Boolean getBajaLogica() {
		return this.bajaLogica;
	}

	public void setBajaLogica(Boolean bajaLogica) {
		this.bajaLogica = bajaLogica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 10)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
	public List<Personal> getPersonales() {
		return personales;
	}

	public void setPersonales(List<Personal> personales) {
		this.personales = personales;
	}

}
