package eu.eurogestion.ese.domain;
// Generated 11-feb-2019 14:05:28 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "eSe")
public class Perfil implements java.io.Serializable {

	private Integer idPerfil;
	private String nombre;
	private TipoPermiso permiso;
	private Opcion opcion;
	private List<Rol> roles;

	public Perfil() {
	}

	public Perfil(String nombre, TipoPermiso idPermiso, Opcion opcion, List<Rol> roles) {
		this.nombre = nombre;
		this.permiso = idPermiso;
		this.opcion = opcion;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_perfil", unique = true, nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToOne
	@JoinColumn(name = "id_permiso", nullable = false)
	public TipoPermiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(TipoPermiso idPermiso) {
		this.permiso = idPermiso;
	}

	@ManyToOne
	@JoinColumn(name = "id_opcion", nullable = false)
	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public List<Rol> getRoles() {
		return roles;
	}

	public void setRoles(List<Rol> roles) {
		this.roles = roles;
	}

}
