package eu.eurogestion.ese.domain;
// Generated 11-feb-2019 14:05:28 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name = "personal", catalog = "eSe")
public class Personal implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idPersonal;
	private String documento;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private Date fechaNac;
	private String tipoVia;
	private String via;
	private Integer numero;
	private Integer planta;
	private String puerta;
	private String nombreUsuario;
	private Compania compania;
	private Cargo cargo;
	private Boolean bajaLogica;
	private Date fechaBaja;
	private List<Rol> roles;
	private String clave;
	private String licencia;
	private String docEmpresa;

	public Personal() {
	}

	public Personal(String documento, String nombreUsuario) {
		this.documento = documento;
		this.nombreUsuario = nombreUsuario;
	}

	public Personal(String documento, String nombre, String apellido1, String apellido2, Date fechaNac, String tipoVia,
			String via, Integer numero, Integer planta, String puerta, String nombreUsuario, Compania compania,
			Cargo cargo, Boolean bajaLogica, Date fechaBaja, List<Rol> roles, String clave, String licencia,
			String docEmpresa) {
		this.documento = documento;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.fechaNac = fechaNac;
		this.tipoVia = tipoVia;
		this.via = via;
		this.numero = numero;
		this.planta = planta;
		this.puerta = puerta;
		this.nombreUsuario = nombreUsuario;
		this.compania = compania;
		this.cargo = cargo;
		this.bajaLogica = bajaLogica;
		this.fechaBaja = fechaBaja;
		this.roles = roles;
		this.clave = clave;
		this.licencia = licencia;
		this.docEmpresa = docEmpresa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_personal", unique = true, nullable = false)
	public Integer getIdPersonal() {
		return this.idPersonal;
	}

	public void setIdPersonal(Integer idPersonal) {
		this.idPersonal = idPersonal;
	}

	@Column(name = "documento", nullable = false, length = 14)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", length = 30)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 30)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nac", length = 10)
	public Date getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(Date fechaNac) {
		this.fechaNac = fechaNac;
	}

	@Column(name = "tipo_via", length = 10)
	public String getTipoVia() {
		return this.tipoVia;
	}

	public void setTipoVia(String tipoVia) {
		this.tipoVia = tipoVia;
	}

	@Column(name = "via", length = 30)
	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "planta")
	public Integer getPlanta() {
		return this.planta;
	}

	public void setPlanta(Integer planta) {
		this.planta = planta;
	}

	@Column(name = "puerta", length = 2)
	public String getPuerta() {
		return this.puerta;
	}

	public void setPuerta(String puerta) {
		this.puerta = puerta;
	}

	@Column(name = "nombre_usuario", nullable = false, length = 20)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@ManyToOne
	@JoinColumn(name = "id_compania", nullable = false)
	public Compania getCompania() {
		return this.compania;
	}

	public void setCompania(Compania compania) {
		this.compania = compania;
	}

	@ManyToOne
	@JoinColumn(name = "id_cargo", nullable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@Column(name = "baja_logica")
	public Boolean getBajaLogica() {
		return this.bajaLogica;
	}

	public void setBajaLogica(Boolean bajaLogica) {
		this.bajaLogica = bajaLogica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_baja", length = 10)
	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personal")
	public List<Rol> getRoles() {
		return roles;
	}

	public void setRoles(List<Rol> roles) {
		this.roles = roles;
	}

	@Column(name = "clave")
	public String getClave() {
		return clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "licencia")
	public String getLicencia() {
		return licencia;
	}

	public void setLicencia(String licencia) {
		this.licencia = licencia;
	}

	@Column(name = "doc_empresa")
	public String getDocEmpresa() {
		return docEmpresa;
	}

	public void setDocEmpresa(String docEmpresa) {
		this.docEmpresa = docEmpresa;
	}

}
