package eu.eurogestion.ese.domain;
// Generated 11-feb-2019 14:05:28 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "eSe")
public class Rol implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idRol;
	private Personal personal;
	private Perfil perfil;

	public Rol() {
	}

	public Rol(Personal idPersonal, Perfil idPermiso) {
		this.personal = idPersonal;
		this.perfil = idPermiso;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_rol", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@ManyToOne
	@JoinColumn(name = "id_personal")
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal idPersonal) {
		this.personal = idPersonal;
	}

	@ManyToOne
	@JoinColumn(name = "id_perfil")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil idPerfil) {
		this.perfil = idPerfil;
	}

}
